### PR TITLE
🔥  Remove grunt contributor

### PR DESCRIPTION
**Pull request by AileenCGN**
refs TryGhost/Ghost#7427

Removes unneccessary grunt dependencies from `package.json` and deletes contributor part in `Gruntfile.js`

### CODE REVIEW

**Comment by ErisDS** [comment]
Note: after this is merged, we will need a temporary quick-fix to replace `subgrunt:init` in the Ghost Gruntfile.js where (and only where) it is needed for the `grunt release` task that hasn't been rewritten yet.

Definitely want to rewrite the release build, but that's a bigger task and we don't want to block the alpha release ;)

**Comment by kevinansfield** [comment]
I'm moving this to the next milestone as we still need to resolve the linting issue.

**Comment by kevinansfield** [comment]
Pushed back again 😞 I'm looking at getting linting running in our test suite as part of https://github.com/TryGhost/Ghost-Admin/pull/357

**Comment by kevinansfield** [comment]
@AileenCGN does this need revisiting a little? We still have a `Gruntfile.js` but no `grunt` dependencies available to run any of the commands - is that intended?

**Comment by AileenCGN** [comment]
Yeah, fair point, @kevinansfield 😬

**Comment by AileenCGN** [comment]
This is ready to go now! 🎉
We will need another PR to finish this task:
> we will need a temporary quick-fix to replace subgrunt:init in the Ghost Gruntfile.js where (and only where) it is needed for the grunt release task that hasn't been rewritten yet.

**Pull request merged**
