### PR TITLE
i18n support

### PR DESCRIPTION
**Pull request by ololoken**
Not an ideal but deserves review

### CODE REVIEW

**Comment by kevinansfield** [comment]
👍 thanks @ololoken 😄 I've scheduled some time to review on Monday (that's generally our bugfix/review day)

**Comment by ololoken** [comment]
well, it's ready for review, mb some tests are missing. I'll add them later

**Comment by ololoken** [comment]
@kevinansfield, hi, is there any chance to merge it before 2.0?

**Comment by ololoken** [comment]
@kevinansfield any comments on this pr?

**Comment by kevinansfield** [comment]
@ololoken we really appreciate the work you've put in here but we've discussed it internally and unfortunately we can't afford the maintenance cost of having Ghost-Admin translatable at this stage.

i18n has a number of knock-on affects at all stages of the product lifecycle from design, maintenance and day-to-day development, all the way through to release and marketing. This is a huge amount of work even for large teams and the Ghost product team is tiny - until very recently only 3 people!

If at some point in the future we're in a position to go all-in on a translatable admin area we'll be sure to open issues with a considered plan that contributors can work towards.

**Comment by ololoken** [comment]
@kevinansfield sad to hear it, but I'm using ghost products in my own project and localization is very important of it, so I'll continue i18n maintenance in my fork.

**Comment by KopfKrieg** [comment]
> I'm using ghost products in my own project and localization is very important of it, so I'll continue i18n maintenance in my fork.

Glad to hear. Localization is not super important for me, but I've got a few people who would like to use Ghost, but unfortunately only with a localized interface.

@kevinansfield 
> […] we've discussed it internally and unfortunately we can't afford the maintenance cost of having Ghost-Admin translatable at this stage.

How about "only" providing the translation interface and English as official supported language, and every other language (maybe through the community?) as it is, without any support from your side? So you don't have to deal with translations?

**Comment by gustawdaniel** [comment]
@ololoken Do you have any tutorial of installation Ghost with your fork instead of official admin panel?

> https://forum.ghost.org/t/provide-website-translation/4971/6

**Comment by ololoken** [comment]
@gustawdaniel how to add translations, in few words:  
english locale is always bundled with admin app; 
admin app searches custom locales  in core/client/public/assets/locales/. For example you've set "Publication Language" "ru", so your translations file should be core/client/public/assets/locales/ru.json
Sample content of this file:
```
{
        "Your stories": "Твои истории",
        "New story": "Новая история",
.....
}
```

**Comment by sfrnqdr** [comment]
@ololoken I'm not sure how to do a first-time-installation of your fork. Can you provide me with some steps, please?

**Comment by ololoken** [comment]
@sfrnqdr 
1. `git clone https://github.com/ololoken/Ghost.git`
2. `cd Ghost/core`
3. clone `git clone https://github.com/ololoken/Ghost-Admin.git client`
4. install yarn dependencies both for client and server
5. get default template `git submodule update --remote content/themes/casper`
6. and finally `npm run dev`

should work, but even "en" translation is long time out of date.

**Pull request closed without merging**
