### PR TITLE
recognise => recognize and add a period at the end

### PR DESCRIPTION
**Pull request by BenMorganIO**
While going through the admin, I noticed that there was a spelling mistake. Also, a sentence started with a capital, but didn't end with a period. :p

https://www.google.ca/webhp#q=define:recognize

### CODE REVIEW

**Comment by acburdine** [comment]
@BenMorganIO That's UK spelling haha 😄

**Comment by BenMorganIO** [comment]
@acburdine lol. At least the period counts.

Maybe we could get i18n into the admin via https://github.com/jamesarosen/ember-i18n?

**Comment by acburdine** [comment]
Yeah, although most times there's not a period it's intentional 😄 And as far as i18n goes there's an issue here: https://github.com/TryGhost/Ghost/issues/5345

**Comment by ErisDS** [comment]
Thanks @BenMorganIO for taking the time to do this. I am going to close this however as the spelling and grammar are as they were intended to be.

**Pull request closed without merging**
