### PR TITLE
🐛  Make `cmd+s` work for all save-buttons

### PR DESCRIPTION
**Pull request by AileenCGN**
closes TryGhost/Ghost#8443

Fixes a bug where the keyboard shortcut `cmd+s` would cause a `Maximum call stack size` error and not save.
Wherever there is a `save` button, the keyboard shortcut to save works now.

### CODE REVIEW

**Comment by AileenCGN** [comment]
Awesome!! Will adapt it for the other changes as well!

**Comment by AileenCGN** [comment]
Added tests @kevinansfield to wherever we have a `save` button.

**Comment by AileenCGN** [comment]
Hmmm.... That's weird... The tests pass all locally... 🤔

**Comment by kevinansfield** [comment]
It's ✅! 😁

**Pull request merged**
