### PR TITLE
[WIP] Convert tags-input (selectize => ember-power-select)

### PR DESCRIPTION
**Pull request by acburdine**
refs TryGhost/Ghost#6458

TODO:
- [x] initial conversion
- [x] css fixes
- [ ] tests
- [x] remove ~~jquery-ui~~ & selectize :tada:  
- [ ] fix the :trollface: edge case that I keep seeing

### CODE REVIEW

**Comment by acburdine** [comment]
Currently blocked on https://github.com/jgwhite/ember-sortable/issues/37

**Comment by mschinis** [comment]
@acburdine We also ran into this issue today at [Trouva](https://www.trouva.com).  Are you interested tackling this together?

**Comment by acburdine** [comment]
@mschinis Sure! How do you want to go about doing that?

One of the things with Ghost's implementation though is it can't be scrolling, it needs to actually handle multiple lines, which introduces some complexity. I've been playing around with ember-sortable, trying to modify it to where it will do both the x and y direction.

**Comment by mschinis** [comment]
I completely agree, ember-sortable needs to be able to handle both x and y directions and not be scrollable.

I will start playing around with ember-sortable myself over the next couple of days, figure out how it works and we can then chat to find a solution. I will email you through your public email on github and we can get working on it!

**Comment by acburdine** [comment]
@mschinis sorry it's been so long - are you still interested in working on this? As a sidenote, I've recently started to help maintain ember-sortable, so once it gets figured out I can release a new version.

I've had some ideas as to how to implement this as well, and will hopefully get some work done this week on implementing it.

**Comment by mschinis** [comment]
@acburdine Yeap - still interested. Things have been super busy last couple of months but will have more time now that Christmas is over.

How do you wanna do this?

**Comment by acburdine** [comment]
@mschinis I'll send you an email in a bit :)

**Comment by acburdine** [comment]
Pretty sure this PR isn't needed anymore since we aren't using selectize 😄

**Pull request closed without merging**
