### PR TITLE
🎨  User profile settings page layout updates

### PR DESCRIPTION
**Pull request by AileenCGN**
closes TryGhost/Ghost#7134

Overhaul of the user settings page to make it more consistent with other settings panels.
The hardly readable validation for user "Full Name" is redundant as well, as the input field for it now has the same styles as the other input fields.

image

### CODE REVIEW

**Comment by AileenCGN** [comment]
What would you reckon it should be? Right now, it looks (afaik) the same as before:

old:
image

new:
image

**Comment by kevinansfield** [comment]
I think it should be the same width as the other inputs. If we want to keep it the same width as it is now then we'd need to add a wrapper around the entire field so that the char count sits at the bottom left of the input instead of out at the side of the screen by itself.

**Comment by JohnONolan** [comment]
agree w/ kevin, except

> so that the char count sits at the bottom left of the input

bottom right

**Comment by kevinansfield** [comment]
> bottom right

:trollface:

/me needs more caffeine

**Comment by AileenCGN** [comment]
image

@kevinansfield, @JohnONolan changes are done!

**Comment by kevinansfield** [comment]
@AileenCGN looks good, only thing left is an update to the tests which are looking for specific colours on the word count

**Pull request merged**
