### PR TITLE
Fix focusing URL field of the "new nav item" row causes validation er…

### PR DESCRIPTION
**Pull request by shawnheide**
- [x] Commit message has a short title & issue references
- [x] Commits are squashed 
- [x] The build will pass

Closes #7140

-change navigation-item model to check if url is identical to '/' instead of blank since blank values are overwritten by '/' before checks

### CODE REVIEW

**Comment by acburdine** [comment]
@shawnheide can you please update the commit message to target Ghost itself?

e.g. `closes TryGhost/Ghost#7140` instead of `closes #7140`

Thanks! 😄

**Comment by shawnheide** [comment]
Yep, no problem. Thanks for letting me know.

**Comment by shawnheide** [comment]
Looks like I accidentally ran the tests under my Ghost fork instead of Ghost-Admin. The Travis tests failed because the url is hardcoded as blank in some of the tests, even though it seems that this can't happen in practice. One option is to just add the 'isBlank(url)' back to the 'isBlank' validation:
``` javascript
return isBlank(label) && (isBlank(url) || url === '/)';
```
I ran the tests, properly this time, and everything passed with this change. 

The other option would be to rewrite the tests, replacing the expected blanks with '/'. Any thoughts on the best way to move forward with this?

**Comment by shawnheide** [comment]
@acburdine Any suggestions on how to proceed?

**Comment by acburdine** [comment]
@shawnheide Sorry for not getting to this sooner. Unfortunately @dbalders stole your ⚡ a little bit on the issue, however his fix introduced another bug, which if you're willing it would be great to fix!

If you're interested, see [this comment](https://github.com/TryGhost/Ghost/issues/7140#issuecomment-238024478) for details on the new bug.

Let me know if you have any more questions 😄

**Comment by dbalders** [comment]
Sorry about that @shawnheide. didn't see yours when I pr'd.

**Comment by shawnheide** [comment]
No worries. It was interesting to see that we had separate ways of fixing it. Cheers.

**Pull request closed without merging**
