### PR TITLE
Fix blank signup screen

### PR DESCRIPTION
**Pull request by kevinansfield**
closes https://github.com/TryGhost/Ghost/issues/7117
- adds guard to `sanitizeInput` method of `gh-trim-focus-input` for null/undefined values
- adds acceptance test for successful signup screen flow
- removes unneeded validation/update handling for a non-editable email field
- adds "At least 8 characters" placeholder to password field
- fixes enter key not submitting the form when name or password field has focus

### CODE REVIEW

**Comment by acburdine** [comment]
@kevinansfield there seems to be a legitimate test bug here. Chrome and Firefox are disconnecting it appears before all the tests are run 😞

**Comment by kevinansfield** [comment]
Very strange, seems like there is a test interdependency somewhere between one of the Settings acceptance tests and the Signup acceptance test. Hopefully it won't take too long to fully track down.

**Comment by kevinansfield** [comment]
I was missing a mocked request in Mirage, no idea why the infinite loop was only occurring when the Navigation, Slack, and Tags tests were running first, removing any one of those resulted in the test running fine 😕.

Error handling in the Signup route when the attempt to check the validity of an invitation fails probably wants looking at but I think it's OK for now.

**Comment by acburdine** [comment]
Ok :smile: a lot of that behavior has been re-worked as part of the validations refactor, so hopefully that should clean a lot of those issues up.

**Comment by acburdine** [comment]
Hey so I just reviewed this and looks good 👍 However, there are some slight UI bugs that exist on the signup page that might be good to get in this PR. Bugs that I found:

- No placeholder in password field (looks different than the other two fields)
- Pressing "enter" in the password field doesn't complete the form if the field is valid (haven't checked the other two fields but might be the same)

If we want to just merge this one I can create another PR in a bit with fixes for the actual page

**Comment by kevinansfield** [comment]
> No placeholder in password field (looks different than the other two fields)

I'm not sure a placeholder is needed here? The form has labels above the inputs and we don't want to suggest a password as people will undoubtedly just copy it. What text were you thinking of using for the placeholder?

**Comment by acburdine** [comment]
I was just thinking "Password". My initial though though was that because the other fields have placeholders it just looked out-of-place for the password field to not have one.

**Comment by kevinansfield** [comment]
Maybe follow the example in Setup and use "At least 8 characters". I'll add that and an enter key fix to this PR, I already have the files open 😄

**Comment by kevinansfield** [comment]
⚡ ready for review again 😄

**Comment by acburdine** [comment]
LGTM 👍

**Pull request merged**
