### PR TITLE
[WIP] User profile settings page layout updates

### PR DESCRIPTION
**Pull request by Circa75**
Just playing around with updating the user profile page layout, making
it more consistent with other settings panels. Also, just making sure
I’m editing files and submitting pull requests properly. Probably
shouldn’t actually pull this in 😉

### CODE REVIEW

**Comment by jmitchell38488** [comment]
`master` ?

**Comment by kevinansfield** [comment]
Hey @Circa75 👋 Changes look good! 😊 Regarding the PR, we have a particular [commit message format](https://github.com/TryGhost/Ghost/wiki/Git-workflow#notes-on-writing-good-commit-messages) but otherwise everything is 👍 

In this instance our CI tests failed - parts of our test suite are quite brittle due to over-reliance on specific CSS selectors and is something we're attempting to rectify as issues come up. I'm not sure how comfortable you are with making changes on that side of things but feel free to ping any of us on Slack or ask on here at any time if you have questions 😄

**Comment by kevinansfield** [comment]
I think what @jmitchell38488 was pointing out is that it's generally not a great idea to submit PRs directly from the `master` branch on your fork.

Best practice is to create a "feature branch" from `master` for each PR, that ensures you can keep your `master` branch up to date with the latest changes in the core repository and you can open multiple PRs easily.

**Comment by AileenCGN** [comment]
Hey @Circa75! I picked your changes and made a new PR where I also adjusted the tests to reflect the changes. Closing this PR in favour of #695

**Pull request closed without merging**
