### PR TITLE
Bump minor dependencies

### PR DESCRIPTION
**Pull request by kevinansfield**
no issue
- ember/ember-data/ember-cli@2.16
- bump all outdated dependencies that do not require additional work or more extensive tests
- bump sub-dependencies in yarn.lock
- use `broccoli-uglify-sourcemap` (same dep as already used in `ember-cli-uglify`) instead of a separate `broccoli-uglify-js` package for building production codemirror assets
- add `/concat-stats-for` to `.gitignore` so that filesize stats from `CONCAT_STATS=true ember build` don't end up in the repo

### CODE REVIEW

**Comment by kevinansfield** [comment]
On hold waiting for Ember Data 2.16.1 which will include a fix for Node 4.x compatibility that the Travis build is currently failing on.

**Comment by kevinansfield** [comment]
Updated with Ember Data 2.16.1, 🤞Travis is ✅ this time 😄

**Comment by kirrg001** [comment]
> The Travis CI build failed

😬 I restarted already, didn't help.

**Comment by kirrg001** [comment]
Oh wait maybe it's the cache :D

**Comment by kevinansfield** [comment]
Whoops, thought this had already been merged so force-pushed over the top 😞 Please hold off for a moment whilst I get the `broccoli-uglify-sourcemap` changes back in

**Comment by kirrg001** [comment]
Wasn't able to merge, was red. Ping me again if it can be merged

**Comment by kevinansfield** [comment]
@kirrg001 good to go now 👍 It's greeeeeen 💚😄

**Pull request merged**
