### PR TITLE
Convert inputs to one way components

### PR DESCRIPTION
**Pull request by acburdine**
This is a precursor for #17 

Converts all inputs from the ember `{{input}}` components to one way inputs.

TODO:
- [x] Fix issues with trim-focus-input
- [x] Ensure all replaced components work correctly
- [x] fix tests

### CODE REVIEW

**Comment by acburdine** [comment]
@kevinansfield this should be good to go now, although it might be worth a glance through the codebase to make sure I got them all 😉

**Comment by acburdine** [comment]
cycled to get Travis to pick changes up

**Comment by kevinansfield** [comment]
👍 LGTM. Could you rename `tests/integration/components/gh-trim-focus-input_test.js` to `tests/integration/components/gh-trim-focus-input-test.js` and rebase? I think it's good to go then.

**Comment by acburdine** [comment]
@kevinansfield done 😄

**Pull request merged**
