### PR TITLE
Long theme names break themes table layout (#7373)

### PR DESCRIPTION
**Pull request by zewish**
fixed

### CODE REVIEW

**Comment by kevinansfield** [comment]
Thanks @zewish, at first glance your fix looks good, I'll get around to testing it properly later 😄 In the meantime would you mind updating your commit and PR content to match our [commit message format](https://github.com/TryGhost/Ghost/wiki/Git-workflow#notes-on-writing-good-commit-messages)?

**Comment by zewish** [comment]
Commit message updated.

**Comment by KennethAshley** [comment]
@zewish Nice fix. I didn't even think to use `text-overflow: ellipsis;`. 

Here was my css only flexbox fix.

Desktop
image

Mobile
image

**Comment by kevinansfield** [comment]
@zewish, @KennethAshley thanks to both of you for taking a stab at this! 😄 After reviewing and seeing the results of @KennethAshley's approach I think that is probably the better direction as it doesn't hide any information, especially as the version numbers are the parts likely to be hidden using ellipsis and they are what's used to differentiate duplicate theme names in the list.

@KennethAshley are you able to PR the approach that you took?

**Pull request closed without merging**
