### PR TITLE
Multi line title.

### PR DESCRIPTION
**Pull request by disordinary**
The title is now a contenteditable div which stretches and wraps to behave like the editor.

It also tries to seamlessly move the cursor between the editor and title to make one coherent editing experience.

Refs: https://github.com/TryGhost/Ghost/issues/7754

### CODE REVIEW

**Comment by kevinansfield** [comment]
I can merge as it'll be good to get more people using it but I think there might still be some tweaks needed?

- At least in Chrome the up/down cursor positioning jumps doesn't seem to work but it is possible to use up/down to move between the two elements
- `{{gh-title}}` should probably be an addon `{{kg-title}}` component
- I'm not sure we need to be using `{{gh-view-title}}` for the editor title - it means we now have nested `<h2>` elements and I believe the old mobile menu button that it includes should be going away now that we have the buttons at the bottom of the screen on mobile

**Comment by disordinary** [comment]
There is an issue around the up and down positioning, Up doesn't work because for some reason the content editable no longer responds to text input in Firefox after the range is manually created in it. We decided simply to merge it and spend some time on it when more important tasks were finished. There is an issue relating to it here: https://github.com/TryGhost/Ghost/issues/8191

The tagname on {{gh-title}} should definitely be a div, I'll fix that, re-name the component, and re-commit.

**Comment by kevinansfield** [comment]
@disordinary I'm hitting infinite loops when editing the title 😕 Chrome becomes unresponsive pretty quickly but what I could see was pointing to the [MutationObserver](https://github.com/TryGhost/Ghost-Admin/pull/595/files#diff-5a33961d0f7d93199e80e7817522d03fR68)

**Comment by disordinary** [comment]
I'm not seeing them at all, what are you doing trigger it?

**Comment by disordinary** [comment]
Hmmm, maybe extensions like the gramarly extension could do it?  It creates HTML mutations that the editor will try and remove because it only wants a plain text title.

Do you have any extensions that might cause mutations?

I'll fix that possibility.

**Comment by kevinansfield** [comment]
No extensions that I know of but I've just tried again without your latest commit and I'm not able to reproduce, no idea what Chrome was doing earlier but even through multiple restarts it was freezing up 😕 

Is there a chance that the latest commit has broken the title event handling in Chrome or is the Travis failure a bit of a random error?

**Comment by disordinary** [comment]
Visually it's working, I ran the tests again and it failed somewhere else. I'm running them a third time so we'll see.

**Pull request merged**
